version: 2

sources:
  - name: staging   
    schema: public          
    tables:
      - name: productos_base
      - name: clientes_base
      - name: ordenes_base

models:
  - name: clientes
    description: Tabla limpia de clientes
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: estado
        tests:
          - accepted_values:
              values: ['activa', 'inactiva']

  - name: ordenes
    description: Tabla de órdenes
    columns:
      - name: orden_id
        tests:
          - unique
          - not_null
      - name: cliente_id
        tests:
          - relationships:
              to: ref('clientes')
              field: id

  - name: productos
    description: Tabla de productos
    columns:
      - name: producto_id
        tests:
          - unique
          - not_null
