version: 2

models:
  - name: clientes
    description: "Listado de clientes"
    columns:
      - name: cliente_id
        tests:
          - not_null
          - unique
      - name: estado
        tests:
          - accepted_values:
              values: ['activa', 'inactiva']

  - name: productos
    description: "Catálogo de productos"
    columns:
      - name: producto_id
        tests:
          - not_null
          - unique

  - name: ventas
    description: "Detalle de ventas"
    columns:
      - name: venta_id
        tests:
          - not_null
          - unique
      - name: cliente_id
        tests:
          - not_null
          - relationships:
              to: ref('clientes')
              field: cliente_id
      - name: producto_id
        tests:
          - not_null
          - relationships:
              to: ref('productos')
              field: producto_id
      - name: monto
        tests:
          - not_null
